version: '3'
services:
  nginx:
    image: nginx:alpine
    environment:
      - SITES_PORT
      - SITES_ROOT
    volumes:
      - ./config/sites:/etc/nginx/conf.d
      - ${SITES_ROOT}:/var/www/sites
    ports:
      - "${SITES_PORT}:80"
    links:
      - php
  mariadb:
    image: mariadb
    environment:
      - HOME
      - DB_PORT
      - MYSQL_ROOT_PASSWORD="changeme"
    volumes:
      - ddds_db:/var/lib/mysql
      - ./config/databases:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
  php:
    image: aloyr/php
    environment:
      - SITES_ROOT
    volumes:
      - ${SITES_ROOT}:/var/www/sites
      - ./lib/drush:/usr/local/bin/drush
      - ./lib/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    expose:
      - "9000"
    links:
      - mariadb
      - redis
  redis:
    image: redis:alpine
    expose:
      - "6379"
  dns:
    image: ruudud/devdns
    environment:
      - HOSTMACHINE_IP="172.16.123.45"
    ports:
      - "53:53/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  ddds_db:
    labels:
      - "persistent"
